module.exports = {
    INDEX_WELCOME: 'welcome use koa api',
    REQ_PARAM_ERROR: '请求参数错误',
    HEADER_ERROR: '头部参数错误',
    NOT_SUPPORT_ROLE: '不支持的角色类型',
    ACCOUNT_NOT_EXIST: '账号不存在',
    ACCOUNT_FORBIDDEN: '账号禁用',
    SQL_EXECUTE_ERROR: 'SQL执行出错',
    ACCOUNT_OR_PASSWD_ERROR: '账号或密码有误',
    PERMISSION_DENIED: '权限拒绝',
    QUERY_FAILED: "查询失败",
    INSERT_FAILED: "新增失败",
    UPDATE_FAILED: "更新失败",
    DELETE_FAILED: "删除失败",
    DATA_DUPLICATE: "数据重复冲突",
    NOTHING_CHANGED: "没有任何修改",
    NOT_LOGIN: '登录失效',
}